"""Borrow return_date columt date|none allow value and default none (model)

Revision ID: f32fa3918278
Revises: 2d032681b86d
Create Date: 2024-12-14 21:25:55.677948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32fa3918278'
down_revision: Union[str, None] = '2d032681b86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
