"""Change created_at and updated_at column type UTC and replace tzinfo=none

Revision ID: 386c336fc453
Revises: 76772b7c5814
Create Date: 2024-12-14 17:36:38.265287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386c336fc453'
down_revision: Union[str, None] = '76772b7c5814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
