"""Add is_active field to borrow

Revision ID: 83df51233f7d
Revises: df41e9c68753
Create Date: 2024-12-13 17:51:29.639290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83df51233f7d'
down_revision: Union[str, None] = 'df41e9c68753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow', 'is_active')
    # ### end Alembic commands ###
