"""birtdate to sqlalchemy.DateTime

Revision ID: 9694ab2b5fe7
Revises: 19d7bc7cbe4b
Create Date: 2024-12-11 00:25:04.477230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9694ab2b5fe7'
down_revision: Union[str, None] = '19d7bc7cbe4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
