"""Borrow return_date columt date|none allow value and default none

Revision ID: 2d032681b86d
Revises: 04b608dfb588
Create Date: 2024-12-14 20:08:11.718551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d032681b86d'
down_revision: Union[str, None] = '04b608dfb588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow', 'return_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow', 'return_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
