"""Add created_at and updated_at columns

Revision ID: 76772b7c5814
Revises: 229a82762f4d
Create Date: 2024-12-13 18:00:50.378542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76772b7c5814'
down_revision: Union[str, None] = '229a82762f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('author', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('book', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('book', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('borrow', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('borrow', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow', 'updated_at')
    op.drop_column('borrow', 'created_at')
    op.drop_column('book', 'updated_at')
    op.drop_column('book', 'created_at')
    op.drop_column('author', 'updated_at')
    op.drop_column('author', 'created_at')
    # ### end Alembic commands ###
