"""Change created_at and updated_at column type UTC and replace tzinfo=none (lambda)

Revision ID: 04b608dfb588
Revises: 386c336fc453
Create Date: 2024-12-14 17:38:30.542476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b608dfb588'
down_revision: Union[str, None] = '386c336fc453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
